name: pytorch2
channels:
  - pytorch
  - anaconda
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - anyio=4.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cuda-cccl=12.5.39
  - cuda-cccl_win-64=12.5.39
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.5.39
  - cuda-runtime=11.8.0
  - cuda-version=12.5
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.6.2
  - filelock=3.13.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.3.1
  - glib=2.80.2
  - glib-tools=2.80.2
  - gst-plugins-base=1.24.5
  - gstreamer=1.24.5
  - icc_rt=2022.1.0
  - icu=73.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.25.0
  - jedi=0.18.1
  - jinja2=3.1.4
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=18.1.8
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.6.39
  - libcurand-dev=10.3.6.39
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.4
  - libglib=2.80.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.5
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libtiff=4.6.0
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.3.1
  - lightning-utilities=0.9.0
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.3
  - matplotlib=3.9.0
  - matplotlib-base=3.9.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.44
  - pillow=10.2.0
  - pip=24.0
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pthread-stubs=0.3
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytorch=2.3.1
  - pytorch-cuda=11.8
  - pytorch-lightning=2.3.0
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qhull=2020.2
  - qt-main=5.15.8
  - referencing=0.30.2
  - requests=2.32.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scipy=1.11.3
  - send2trash=1.8.2
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - torchmetrics=1.4.0.post0
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ucrt=10.0.20348.0
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zstd=1.5.6
  - pip:
      - torchaudio==2.3.1
      - torchvision==0.18.1
